"""Generate slack-app-manifest.yaml with one slash command per skill.

Slack caps apps at 25 slash commands, so pass the skills you want
autocomplete for (or edit CURATED below). All other skills still work when
typed — the gateway forwards any unknown /command to Copilot as a skill
invocation; it just won't autocomplete.

Usage:
    python scripts/gen_manifest.py                 # built-in commands
    python scripts/gen_manifest.py skill-one ...   # explicit set

Set COPILOT_SKILLS_DIR to read descriptions from local skill files.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

SKILLS_DIR = (
    Path(os.environ["COPILOT_SKILLS_DIR"]).expanduser()
    if os.environ.get("COPILOT_SKILLS_DIR")
    else None
)
MANIFEST = Path(__file__).resolve().parent.parent / "slack-app-manifest.yaml"
MAX_COMMANDS = 25

CURATED = ["new", "stop", "status", "help"]
BUILTIN_DESCRIPTIONS = {
    "new": "Start a fresh Copilot session",
    "stop": "Cancel the active Copilot prompt",
    "status": "Show the current Copilot session status",
    "help": "Show gateway usage help",
}


def skill_description(name: str) -> str:
    if name in BUILTIN_DESCRIPTIONS:
        return BUILTIN_DESCRIPTIONS[name]
    if SKILLS_DIR is None:
        return f"Invoke the {name} Copilot skill"
    skill_md = SKILLS_DIR / name / "SKILL.md"
    if not skill_md.is_file():
        return f"Invoke the {name} Copilot skill"
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    if text.startswith("---"):
        frontmatter = text[3:].split("---", 1)[0]
        m = re.search(r"^description:\s*(.*)$", frontmatter, re.MULTILINE)
        if m:
            value = m.group(1).strip().strip('"').strip("'")
            if value in (">", "|", ">-", "|-", ">+", "|+"):
                # YAML block scalar: gather following indented lines
                lines = []
                for line in frontmatter[m.end():].splitlines()[1:]:
                    if line.startswith((" ", "\t")) and line.strip():
                        lines.append(line.strip())
                    elif line.strip():
                        break
                value = " ".join(lines)
            if value:
                return value[:150]
    return f"Invoke the {name} Copilot skill"


def command_yaml(name: str) -> str:
    desc = skill_description(name).replace('"', "'")
    return f"""      - command: /{name}
        description: "{desc}"
        should_escape: false
        usage_hint: "[args]\""""


def main() -> int:
    names = sys.argv[1:] or CURATED
    missing = [
        n for n in names
        if n not in BUILTIN_DESCRIPTIONS
        and SKILLS_DIR is not None
        and not (SKILLS_DIR / n / "SKILL.md").is_file()
    ]
    if missing:
        print(f"warning: no SKILL.md for: {', '.join(missing)}", file=sys.stderr)
    if len(names) > MAX_COMMANDS:
        print(f"error: {len(names)} commands > Slack limit of {MAX_COMMANDS}", file=sys.stderr)
        return 1
    bad = [n for n in names if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,31}", n)]
    if bad:
        print(f"error: invalid slash command names: {', '.join(bad)}", file=sys.stderr)
        return 1

    commands = "\n".join(command_yaml(n) for n in names)
    manifest = f"""# GENERATED by scripts/gen_manifest.py — do not edit by hand.
# Regenerate with: python scripts/gen_manifest.py
# Apply changes in your Slack app under Settings -> App Manifest.
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: copilot-gateway
  description: Talk to your local GitHub Copilot CLI from Slack
  background_color: "#1a1a2e"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: copilot-gateway
    always_online: true
  slash_commands:
{commands}
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - chat:write
      - commands
      - im:history
      - im:read
      - im:write
      - users:read
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.im
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
"""
    MANIFEST.write_text(manifest, encoding="utf-8")
    print(f"wrote {MANIFEST} with {len(names)} slash commands")
    print("now: https://api.slack.com/apps -> copilot-gateway -> Settings -> App Manifest -> paste -> Save")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
